/*typedef enum {
    MENSAJE = 1,
    PAQUETE = 2,

    OP_STORAGE_HANDSHAKE = 10,
    OP_STORAGE_CREATE = 11,
    OP_STORAGE_TRUNCATE = 12,
    OP_STORAGE_READ_BLOCK = 13,
    OP_STORAGE_WRITE_BLOCK = 14
} op_code;*/